#!/bin/bash

function overlay_create ()
{
        free=$((`stat -c '%a*%S/1024/1024' -f .`))
        echo free ${free}M
        overlays=""
        overlay_remove
        for d in $DEVICES; do
                b=$(basename /dev/$d)
                size_bkl=$(sudo blockdev --getsz /dev/$d) # in 512 blocks/sectors
                # reserve 1M space for snapshot header
                # ext3 max file length is 2TB   
                truncate -s$((((size_bkl+1)/2)+1024))K $b.ovr || (echo "Do you use ext4?"; return 1)
                loop=$(sudo losetup -f --show -- $b.ovr)
                # https://www.kernel.org/doc/Documentation/device-mapper/snapshot.txt
                sudo dmsetup create $b --table "0 $size_bkl snapshot /dev/$d $loop P 8"
                echo /dev/$d $((size_bkl/2048))M $loop /dev/mapper/$b
                overlays="$overlays /dev/mapper/$b"
        done
        overlays=${overlays# }
}

function overlay_remove ()
{
        for d in $DEVICES; do
                b=$(basename /dev/$d)
                [ -e /dev/mapper/$b ] && sudo dmsetup remove $b && echo /dev/mapper/$b 
                if [ -e $b.ovr ]; then
                        echo $b.ovr
                        l=$(sudo losetup -j $b.ovr | cut -d : -f1)
                        echo $l
                        [ -n "$l" ] && sudo losetup -d $(sudo losetup -j $b.ovr | cut -d : -f1)
                        rm -f $b.ovr &> /dev/null
                fi
        done
}

sudo adduser alex
sudo usermod alex -aG sudo,adm
sudo adduser --group dockergroup
sudo groupmod --gid 1050 dockergroup
sudo adduser dockeruser --uid 1050 --ingroup dockergroup
sudo cp /mnt/sda/home/alex/fstab.temp /etc/fstab
sudo cp /mnt/sda/home/alex/sudoers.temp /etc/sudoers.d/alex
sudo mkdir -p /etc/systemd/system/wsdd.service.d
sudo cp /mnt/sda/home/alex/wsdd-override.temp /etc/systemd/system/wsdd.service.d/override.conf
sudo cp /mnt/sda/etc/apt/sources.list.d/* /etc/apt/sources.list.d/
sudo cp /mnt/sda/etc/apt/trusted.gpg.d/* /etc/apt/trusted.gpg.d/
curl https://packages.grafana.com/gpg.key | sudo apt-key add -
curl http://www.webmin.com/jcameron-key.asc | sudo apt-key add -
curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
curl https://doozer.io/keys/tvheadend/tvheadend/pgp | sudo apt-key add -
curl https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt | sudo apt-key add -
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
curl https://bacula.org/downloads/baculum/baculum.pub | sudo apt-key add -
curl https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
curl https://xpra.org/gpg.asc | sudo apt-key add -
curl https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
curl http://hwraid.le-vert.net/ubuntu/hwraid.le-vert.net.gpg.key | sudo apt-key add -
curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -

sudo add-apt-repository --yes ppa:mamarley/tvheadend-git-stable
sudo cp /mnt/sda/home/alex/.bash_aliases ~/
. ~/.bash_aliases
sudo visudo

sudo mkdir -p /mnt/individual_drives/parity/4TBTO-5430A00IFV94
sudo mkdir -p /mnt/individual_drives/parity/4TBTO-85S0A00HFVL8
sudo mkdir -p /mnt/individual_drives/parity/4TBWD-WMC1F0D3F3U5
sudo mkdir -p /mnt/individual_drives/parity/4TBWD-WMC1F0F4D47N
sudo mkdir -p /mnt/individual_drives/parity/4TBWD-WMC1F0D76X01
sudo mkdir -p /mnt/individual_drives/parity/4TBTO-25E0A02YFVL8
sudo mkdir -p /mnt/individual_drives/data/12TBWD-8DGEPWHY
sudo mkdir -p /mnt/individual_drives/data/12TBWD-8DGESZBH
sudo mkdir -p /mnt/individual_drives/data/10TBWD-1SHUW6TZ
sudo mkdir -p /mnt/individual_drives/data/10TBWD-1SHV2XKZ
sudo mkdir -p /mnt/individual_drives/data/4TBTO-25E0A02QFVL8
sudo mkdir -p /mnt/individual_drives/data/4TBWD-WMC1F0092903
sudo mkdir -p /mnt/individual_drives/data/4TBTO-25E0A02WFVL8
sudo mkdir -p /mnt/individual_drives/data/4TBTO-85B0A00NFVL8
sudo mkdir -p /mnt/videopool
sudo mkdir -p /mnt/ext4-data

if [ "$(grep -lx "deb http://gb.archive.ubuntu.com/ubuntu $(lsb_release -sc) universe" /etc/apt/sources.list)" != "/etc/apt/sources.list" ]
then
    echo deb http://gb.archive.ubuntu.com/ubuntu/ $(lsb_release -sc) universe | sudo tee -a /etc/apt/sources.list
fi
if [ "$(grep -lx "deb http://gb.archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates universe" /etc/apt/sources.list)" != "/etc/apt/sources.list" ]
then
    echo deb http://gb.archive.ubuntu.com/ubuntu/ $(lsb_release -sc)-updates universe | sudo tee -a /etc/apt/sources.list
fi
if [ "$(grep -lx "deb http://gb.archive.ubuntu.com/ubuntu $(lsb_release -sc) multiverse" /etc/apt/sources.list)" != "/etc/apt/sources.list" ]
then
    echo deb http://gb.archive.ubuntu.com/ubuntu/ $(lsb_release -sc) multiverse | sudo tee -a /etc/apt/sources.list
fi
if [ "$(grep -lx "deb http://gb.archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates multiverse" /etc/apt/sources.list)" != "/etc/apt/sources.list" ]
then
    echo deb http://gb.archive.ubuntu.com/ubuntu/ $(lsb_release -sc)-updates multiverse | sudo tee -a /etc/apt/sources.list
fi
sudo apt update
sudo apt install parallel git mdadm openssh-server build-essential samba tgt open-iscsi apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
sudo cp /mnt/sda/etc/mdadm/mdadm.conf /etc/mdadm/
sudo cp /mnt/sda/etc/samba/smb.conf /etc/samba/
#sudo cp /mnt/sda/home/alex/tgt-targets.conf.temp /etc/tgt/tgt.conf
sudo tgtadm --lld iscsi --op new --mode target --tid 1 -T iqn.2019-04.uk.org.alex-wood.bareubuntu:sda
sudo tgtadm --lld iscsi --op new --mode logicalunit --tid 1 --lun 1 -b /dev/sda1
sudo tgtadm --lld iscsi --op bind --mode target --tid 1 -I 192.168.32.0/24
sudo tgt-admin --dump | sudo tee /etc/tgt/conf.d/sda
sudo smbpasswd -a alex
sudo service tgt restart
sudo service smbd restart

cd ~
git clone https://github.com/trapexit/mergerfs.git
cd mergerfs
sudo tools/install-build-pkgs
make deb
cd ..
sudo dpkg -i mergerfs_*.deb

sudo mount -a

git clone https://github.com/christgau/wsdd
sudo ln -s ~/wsdd/src/wsdd.py /usr/bin/wsdd
sudo ln -s ~/wsdd/etc/systemd/wsdd.service /etc/systemd/system/wsdd.service
sudo systemctl daemon-reload
sudo system service wsdd start

wget https://mirrors.edge.kernel.org/pub/linux/utils/raid/mdadm/mdadm-4.1.tar.gz
tar xf mdadm-4.1.tar.gz
cd mdadm-4.1
make
sudo make install
cd ..

sudo mdadm --assemble --scan --readonly
sudo mount -o noload /dev/md0 /mnt/ext4-data
cat /proc/mdstat

sudo umount /mnt/sda
echo sudo iscsiadm -m node --login
echo sudo mount /dev/sdb /mnt/sda

echo for directory in \/mnt\/ext4-data\/\*
echo do
echo     sudo tar --exclude=/mnt/ext4-data/Backups/MAIN-PC --exclude=/mnt/ext4-data/Backups/Config --exclude=/mnt/ext4-data/Audiobooks --exclude=/mnt/ext4-data/\$RECYCLE.BIN -cpvzf \"/mnt/videopool/raid/\$\(basename \$\{directory\}\)-backup.tar.gz\" \"\$\{directory\}\"
echo done
exit 0

UUID=$(sudo mdadm -E /dev/sdi|perl -ne '/Array UUID : (\S+)/ and print $1')
DEVICES=$(cat /proc/partitions | parallel --tagstring {5} --colsep ' +' sudo mdadm -E /dev/{5} |grep $UUID | parallel --colsep '\t' echo /dev/{1})
echo UUID: ${UUID}
echo DEVICES: ${DEVICES}
parallel 'test -e /dev/loop{#} || mknod -m 660 /dev/loop{#} b 7 {#}' ::: $DEVICES
parallel truncate -s4000G overlay-{/} ::: $DEVICES
parallel 'size=$(sudo blockdev --getsize {}); loop=$(sudo losetup -f --show -- overlay-{/}); echo 0 $size snapshot {} $loop P 8 | sudo dmsetup create {/}' ::: $DEVICES
OVERLAYS=$(parallel echo /dev/mapper/{/} ::: $DEVICES)
echo OVERLAYS: ${OVERLAYS}
sudo dmsetup status
parallel --tag -k sudo mdadm -E ::: $OVERLAYS|grep -E 'Update'
parallel --tag -k sudo mdadm -E ::: $OVERLAYS|grep -E 'Role'
# this will start to assemble the arrays with the overlays in place, then pause the assembly to remove the overlays
# (otherwize they will fill up your system drive) then continue on with just the bare drives
# once they have been added back as spares.  Note we are usiong md1 so as not to confuse with the original md0
#sudo mdadm --assemble --force /dev/md1 $OVERLAYS
#echo 0 | sudo tee /proc/sys/dev/raid/speed_limit_max
#echo 0 | sudo tee /proc/sys/dev/raid/speed_limit_min
#parallel -j1 sudo mdadm --add /dev/md1 ::: $OVERLAY
#cat /proc/mdstat
#sudo mdadm --stop /dev/md1
#sudo mdadm --assemble /dev/md1

##undo
#parallel 'sudo dmsetup remove {/}; rm overlay-{/}' ::: $DEVICES
#parallel sudo losetup -d ::: /dev/loop[0-9]*

######mdadm --create --verbose /dev/md0 --uuid=5245ec79:6be76700:4cddf690:5f613e3a --chunk=512 --level=5 --raid-devices=5 <devices>

#cat /proc/mdstat
#Personalities : [raid6] [raid5] [raid4]
#md0 : active (read-only) raid5 sdi[3] sdp[5](S) sdn[6] sdo[4] sdg[2] sdt[1]
#      11720661504 blocks super 1.2 level 5, 512k chunk, algorithm 2 [5/5] [UUUUU]
#        resync=PENDING
#      bitmap: 23/30 pages [92KB], 65536KB chunk

#sudo mdadm -E /dev/sd[ipnogt]
#/dev/sdg:
#          Magic : a92b4efc
#        Version : 1.2
#    Feature Map : 0x45
#     Array UUID : 5245ec79:6be76700:4cddf690:5f613e3a
#           Name : TheMatrix:0
#  Creation Time : Sat Dec 24 01:10:02 2016
#     Raid Level : raid5
#   Raid Devices : 5
#
# Avail Dev Size : 7813775024 (3725.90 GiB 4000.65 GB)
#     Array Size : 15627548672 (14903.59 GiB 16002.61 GB)
#  Used Dev Size : 7813774336 (3725.90 GiB 4000.65 GB)
#    Data Offset : 262144 sectors
#     New Offset : 258048 sectors
#   Super Offset : 8 sectors
#          State : active
#    Device UUID : c970b776:6609bc9a:bd720e0a:326104f0
#
#Internal Bitmap : 8 sectors from superblock
#  Reshape pos'n : 10428905472 (9945.78 GiB 10679.20 GB)
#  Delta Devices : 1 (4->5)
#
#    Update Time : Fri Apr 12 19:50:54 2019
#  Bad Block Log : 512 entries available at offset 72 sectors
#       Checksum : e535efd7 - correct
#         Events : 2471060
#
#         Layout : left-symmetric
#     Chunk Size : 512K
#
#   Device Role : Active device 2
#   Array State : AAAAA ('A' == active, '.' == missing, 'R' == replacing)
#/dev/sdi:
#          Magic : a92b4efc
#        Version : 1.2
#    Feature Map : 0x45
#     Array UUID : 5245ec79:6be76700:4cddf690:5f613e3a
#           Name : TheMatrix:0
#  Creation Time : Sat Dec 24 01:10:02 2016
#     Raid Level : raid5
#   Raid Devices : 5
#
# Avail Dev Size : 7813775024 (3725.90 GiB 4000.65 GB)
#     Array Size : 15627548672 (14903.59 GiB 16002.61 GB)
#  Used Dev Size : 7813774336 (3725.90 GiB 4000.65 GB)
#    Data Offset : 262144 sectors
#     New Offset : 258048 sectors
#   Super Offset : 8 sectors
#          State : active
#    Device UUID : d741dffd:a5df2cb8:90374e87:cd3acc0a
#
#Internal Bitmap : 8 sectors from superblock
#  Reshape pos'n : 10428905472 (9945.78 GiB 10679.20 GB)
#  Delta Devices : 1 (4->5)
#
#    Update Time : Fri Apr 12 19:50:54 2019
#  Bad Block Log : 512 entries available at offset 72 sectors
#       Checksum : 21d63504 - correct
#         Events : 2471060
#
#         Layout : left-symmetric
#     Chunk Size : 512K
#
#   Device Role : Active device 0
#   Array State : AAAAA ('A' == active, '.' == missing, 'R' == replacing)
#/dev/sdn:
#          Magic : a92b4efc
#        Version : 1.2
#    Feature Map : 0x45
#     Array UUID : 5245ec79:6be76700:4cddf690:5f613e3a
#           Name : TheMatrix:0
#  Creation Time : Sat Dec 24 01:10:02 2016
#     Raid Level : raid5
#   Raid Devices : 5
#
# Avail Dev Size : 7813775024 (3725.90 GiB 4000.65 GB)
#     Array Size : 15627548672 (14903.59 GiB 16002.61 GB)
#  Used Dev Size : 7813774336 (3725.90 GiB 4000.65 GB)
#    Data Offset : 262144 sectors
#     New Offset : 258048 sectors
#   Super Offset : 8 sectors
#          State : active
#    Device UUID : c3237171:ec0d616f:ec2e1b8d:0bcb280b
#
#Internal Bitmap : 8 sectors from superblock
#  Reshape pos'n : 10428905472 (9945.78 GiB 10679.20 GB)
#  Delta Devices : 1 (4->5)
#
#    Update Time : Fri Apr 12 19:50:54 2019
#  Bad Block Log : 512 entries available at offset 24 sectors
#       Checksum : 52c5ccab - correct
#         Events : 2471060
#
#         Layout : left-symmetric
#     Chunk Size : 512K
#
#   Device Role : Active device 4
#   Array State : AAAAA ('A' == active, '.' == missing, 'R' == replacing)
#/dev/sdo:
#          Magic : a92b4efc
#        Version : 1.2
#    Feature Map : 0x4d
#     Array UUID : 5245ec79:6be76700:4cddf690:5f613e3a
#           Name : TheMatrix:0
#  Creation Time : Sat Dec 24 01:10:02 2016
#     Raid Level : raid5
#   Raid Devices : 5
#
# Avail Dev Size : 7813775024 (3725.90 GiB 4000.65 GB)
#     Array Size : 15627548672 (14903.59 GiB 16002.61 GB)
#  Used Dev Size : 7813774336 (3725.90 GiB 4000.65 GB)
#    Data Offset : 262144 sectors
#     New Offset : 258048 sectors
#   Super Offset : 8 sectors
#          State : active
#    Device UUID : a8f0afb2:129466fd:a7a62915:fd87a2e5
#
#Internal Bitmap : 8 sectors from superblock
#  Reshape pos'n : 10428905472 (9945.78 GiB 10679.20 GB)
#  Delta Devices : 1 (4->5)
#
#    Update Time : Fri Apr 12 19:50:54 2019
#  Bad Block Log : 512 entries available at offset 24 sectors - bad blocks present.
#       Checksum : 84925462 - correct
#         Events : 2471060
#
#         Layout : left-symmetric
#     Chunk Size : 512K
#
#   Device Role : Active device 3
#   Array State : AAAAA ('A' == active, '.' == missing, 'R' == replacing)
#/dev/sdp:
#          Magic : a92b4efc
#        Version : 1.2
#    Feature Map : 0x45
#     Array UUID : 5245ec79:6be76700:4cddf690:5f613e3a
#           Name : TheMatrix:0
#  Creation Time : Sat Dec 24 01:10:02 2016
#     Raid Level : raid5
#   Raid Devices : 5
#
# Avail Dev Size : 7813775024 (3725.90 GiB 4000.65 GB)
#     Array Size : 15627548672 (14903.59 GiB 16002.61 GB)
#  Used Dev Size : 7813774336 (3725.90 GiB 4000.65 GB)
#    Data Offset : 262144 sectors
#     New Offset : 258048 sectors
#   Super Offset : 8 sectors
#          State : active
#    Device UUID : 8e4d4bf8:96f3fbd8:6115a4eb:3d6e1597
#
#Internal Bitmap : 8 sectors from superblock
#  Reshape pos'n : 10428905472 (9945.78 GiB 10679.20 GB)
#  Delta Devices : 1 (4->5)
#
#    Update Time : Fri Apr 12 15:01:28 2019
#  Bad Block Log : 512 entries available at offset 24 sectors
#       Checksum : 2db021e9 - correct
#         Events : 2471059
#
#         Layout : left-symmetric
#     Chunk Size : 512K
#
#   Device Role : spare
#   Array State : AAAAA ('A' == active, '.' == missing, 'R' == replacing)
#/dev/sdt:
#          Magic : a92b4efc
#        Version : 1.2
#    Feature Map : 0x4d
#     Array UUID : 5245ec79:6be76700:4cddf690:5f613e3a
#           Name : TheMatrix:0
#  Creation Time : Sat Dec 24 01:10:02 2016
#     Raid Level : raid5
#   Raid Devices : 5
#
# Avail Dev Size : 7813775024 (3725.90 GiB 4000.65 GB)
#     Array Size : 15627548672 (14903.59 GiB 16002.61 GB)
#  Used Dev Size : 7813774336 (3725.90 GiB 4000.65 GB)
#    Data Offset : 262144 sectors
#     New Offset : 258048 sectors
#   Super Offset : 8 sectors
#          State : active
#    Device UUID : c825b0d1:9ffa98a6:e631ed68:afbc1421
#
#Internal Bitmap : 8 sectors from superblock
#  Reshape pos'n : 10428905472 (9945.78 GiB 10679.20 GB)
#  Delta Devices : 1 (4->5)
#
#    Update Time : Fri Apr 12 19:50:54 2019
#  Bad Block Log : 512 entries available at offset 72 sectors - bad blocks present.
#       Checksum : dbfab034 - correct
#         Events : 2471060
#
#         Layout : left-symmetric
#     Chunk Size : 512K
#
#   Device Role : Active device 1
#   Array State : AAAAA ('A' == active, '.' == missing, 'R' == replacing)
